### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/chenllos/.atom/projects.cson'

### ISSUE THREAD

**Issue by teamrun** [paulpflug/mocha-ui#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [mocha-ui](https://github.com/paulpflug/mocha-ui) package, v0.1.4
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/chenllos/.atom/projects.cson'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/Users/chenllos/.atom/projects.cson'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Object.module.exports.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:158:21)
  at ProjectManager.module.exports.ProjectManager.getProject (/Users/chenllos/.atom/packages/mocha-ui/lib/project-manager.coffee:18:23)
  at ProjectManager.getProject (/Users/chenllos/.atom/packages/mocha-ui/lib/project-manager.coffee:1:1)
  at ProjectManager.module.exports.ProjectManager.getProjectSetting (/Users/chenllos/.atom/packages/mocha-ui/lib/project-manager.coffee:35:16)
  at ProjectManager.getProjectSetting (/Users/chenllos/.atom/packages/mocha-ui/lib/project-manager.coffee:1:1)
  at ActionBarView.module.exports.ActionBarView.initialize (/Users/chenllos/.atom/packages/mocha-ui/lib/action-bar-view.coffee:33:32)
  at ActionBarView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new ActionBarView (/Users/chenllos/.atom/packages/mocha-ui/lib/action-bar-view.coffee:5:3)
  at Object.content (/Users/chenllos/.atom/packages/mocha-ui/lib/mocha-ui-view.coffee:17:51)
  at Builder.tag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
  at Function.View.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
  at Function.MochaUiView.content (/Users/chenllos/.atom/packages/mocha-ui/lib/mocha-ui-view.coffee:16:6)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156:31)
  at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
  at MochaUiView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155:33)
  at new MochaUiView (/Users/chenllos/.atom/packages/mocha-ui/lib/mocha-ui-view.coffee:15:3)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:87:16)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:61:21)
  at atom-pane.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:210:25)
  at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:60:55)
  at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:125:19)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:615:27)
  at atom-notification.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:290:40)
  at atom-notification.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:248:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:57:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:57:27)
  at atom-notification.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:252:25)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:147:26)

```
### Commands

```
  2x -0:38.3.0 mocha-ui:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "unity-ui",
      "monokai"
    ]
  },
  "mocha-ui": {}
}
```
### Installed Packages

``` coffee
# User
minimap, v4.10.0
mocha-ui, v0.1.4
monokai, v0.14.0
react, v0.12.0
unity-ui, v2.0.11

# Dev
No dev packages
```

**Comment by paulpflug** [comment]
should be resolved in 0.1.5
thanks for reporting :smiley:
